### ISSUE TITLE
Github switched off APIv2

### ISSUE THREAD

**Issue by mibe** [trentm/googlecode2github#3]
Hello,

According to [0], API v2 of github was turned off a few days ago, thus making it impossible to use shadowissues.py.

[0] https://github.com/blog/1090-github-api-moving-on

**Comment by trentm** [comment]
well crap. :)  Realistically I'm not sure when I'll get to updating this code. Patches definitely welcome tho.

**Comment by ebidel** [comment]
Here's a PR for this :) 
https://github.com/trentm/googlecode2github/pull/4

**Comment by trentm** [comment]
Fixed with pull #4. Thanks!

**Comment by ebidel** [comment]
Word up!
